import IntervalService from "../services/interval.service.js";

export default class CompaniesDataService {
  static companies = [{"id":1,"userId":1,"department":"Training","name":"Dabfeed","title":"Editor"},
    {"id":2,"userId":2,"department":"Services","name":"Lajo","title":"Recruiter"},
    {"id":3,"userId":3,"department":"Support","name":"Leexo","title":"Safety Technician II"},
    {"id":4,"userId":4,"department":"Research and Development","name":"Myworks","title":"Compensation Analyst"},
    {"id":5,"userId":5,"department":"Business Development","name":"Twitterbridge","title":"Structural Engineer"},
    {"id":6,"userId":6,"department":"Product Management","name":"Minyx","title":"Nurse"},
    {"id":7,"userId":7,"department":"Training","name":"Vidoo","title":"Automation Specialist II"},
    {"id":8,"userId":8,"department":"Legal","name":"Rhycero","title":"Office Assistant III"},
    {"id":9,"userId":9,"department":"Accounting","name":"Vinder","title":"Human Resources Manager"},
    {"id":10,"userId":10,"department":"Sales","name":"Tagtune","title":"Environmental Tech"},
    {"id":11,"userId":11,"department":"Training","name":"Myworks","title":"Civil Engineer"},
    {"id":12,"userId":12,"department":"Research and Development","name":"Riffpedia","title":"Systems Administrator IV"},
    {"id":13,"userId":13,"department":"Product Management","name":"Yambee","title":"Internal Auditor"},
    {"id":14,"userId":14,"department":"Legal","name":"Kaymbo","title":"Recruiter"},
    {"id":15,"userId":15,"department":"Human Resources","name":"Yamia","title":"Assistant Professor"},
    {"id":16,"userId":16,"department":"Training","name":"Vimbo","title":"VP Accounting"},
    {"id":17,"userId":17,"department":"Training","name":"Babbleopia","title":"Computer Systems Analyst III"},
    {"id":18,"userId":18,"department":"Support","name":"Eabox","title":"Occupational Therapist"},
    {"id":19,"userId":19,"department":"Support","name":"Brainbox","title":"Recruiter"},
    {"id":20,"userId":20,"department":"Sales","name":"Digitube","title":"Media Manager IV"},
    {"id":21,"userId":21,"department":"Business Development","name":"Gigabox","title":"Budget/Accounting Analyst IV"},
    {"id":22,"userId":22,"department":"Legal","name":"Bubblemix","title":"Civil Engineer"},
    {"id":23,"userId":23,"department":"Research and Development","name":"Skinix","title":"Marketing Manager"},
    {"id":24,"userId":24,"department":"Human Resources","name":"Feednation","title":"Environmental Tech"},
    {"id":25,"userId":25,"department":"Support","name":"Bluejam","title":"Senior Financial Analyst"},
    {"id":26,"userId":26,"department":"Human Resources","name":"Youbridge","title":"Administrative Officer"},
    {"id":27,"userId":27,"department":"Training","name":"Cogibox","title":"Food Chemist"},
    {"id":28,"userId":28,"department":"Legal","name":"Kimia","title":"Speech Pathologist"},
    {"id":29,"userId":29,"department":"Research and Development","name":"Tavu","title":"Legal Assistant"},
    {"id":30,"userId":30,"department":"Support","name":"Edgeblab","title":"Budget/Accounting Analyst III"},
    {"id":31,"userId":31,"department":"Training","name":"Tagcat","title":"General Manager"},
    {"id":32,"userId":32,"department":"Business Development","name":"Wordify","title":"Senior Cost Accountant"},
    {"id":33,"userId":33,"department":"Human Resources","name":"Fiveclub","title":"Junior Executive"},
    {"id":34,"userId":34,"department":"Business Development","name":"Fivebridge","title":"Systems Administrator I"},
    {"id":35,"userId":35,"department":"Marketing","name":"Yotz","title":"Web Developer IV"},
    {"id":36,"userId":36,"department":"Marketing","name":"Browsezoom","title":"Community Outreach Specialist"},
    {"id":37,"userId":37,"department":"Training","name":"Skinix","title":"Editor"},
    {"id":38,"userId":38,"department":"Support","name":"Riffpedia","title":"Product Engineer"},
    {"id":39,"userId":39,"department":"Business Development","name":"Yakitri","title":"Senior Quality Engineer"},
    {"id":40,"userId":40,"department":"Legal","name":"Divanoodle","title":"VP Sales"},
    {"id":41,"userId":41,"department":"Sales","name":"Realcube","title":"Data Coordinator"},
    {"id":42,"userId":42,"department":"Product Management","name":"Youopia","title":"Civil Engineer"},
    {"id":43,"userId":43,"department":"Services","name":"Meevee","title":"Marketing Assistant"},
    {"id":44,"userId":44,"department":"Business Development","name":"Yata","title":"Structural Engineer"},
    {"id":45,"userId":45,"department":"Support","name":"Gigaclub","title":"Executive Secretary"},
    {"id":46,"userId":46,"department":"Training","name":"Thoughtworks","title":"Research Assistant II"},
    {"id":47,"userId":47,"department":"Training","name":"Myworks","title":"Electrical Engineer"},
    {"id":48,"userId":48,"department":"Research and Development","name":"Oodoo","title":"Account Executive"},
    {"id":49,"userId":49,"department":"Engineering","name":"Leexo","title":"Marketing Assistant"},
    {"id":50,"userId":50,"department":"Research and Development","name":"Tavu","title":"VP Marketing"},
    {"id":51,"userId":51,"department":"Support","name":"Riffwire","title":"Operator"},
    {"id":52,"userId":52,"department":"Business Development","name":"Avavee","title":"Accounting Assistant II"},
    {"id":53,"userId":53,"department":"Human Resources","name":"Youopia","title":"Engineer II"},
    {"id":54,"userId":54,"department":"Marketing","name":"Oba","title":"Senior Quality Engineer"},
    {"id":55,"userId":55,"department":"Research and Development","name":"Bluejam","title":"Engineer III"},
    {"id":56,"userId":56,"department":"Research and Development","name":"Skimia","title":"VP Sales"},
    {"id":57,"userId":57,"department":"Product Management","name":"Gabvine","title":"Financial Advisor"},
    {"id":58,"userId":58,"department":"Legal","name":"Feedmix","title":"Engineer III"},
    {"id":59,"userId":59,"department":"Support","name":"Linkbridge","title":"Statistician III"},
    {"id":60,"userId":60,"department":"Accounting","name":"Quamba","title":"Marketing Assistant"},
    {"id":61,"userId":61,"department":"Training","name":"Agimba","title":"Marketing Manager"},
    {"id":62,"userId":62,"department":"Human Resources","name":"Skajo","title":"Geological Engineer"},
    {"id":63,"userId":63,"department":"Research and Development","name":"Wikibox","title":"Programmer I"},
    {"id":64,"userId":64,"department":"Legal","name":"Yoveo","title":"Professor"},
    {"id":65,"userId":65,"department":"Product Management","name":"Livefish","title":"Technical Writer"},
    {"id":66,"userId":66,"department":"Engineering","name":"Zoomcast","title":"Human Resources Assistant III"},
    {"id":67,"userId":67,"department":"Accounting","name":"Chatterpoint","title":"Recruiting Manager"},
    {"id":68,"userId":68,"department":"Product Management","name":"Flipstorm","title":"Associate Professor"},
    {"id":69,"userId":69,"department":"Research and Development","name":"Avamm","title":"Budget/Accounting Analyst IV"},
    {"id":70,"userId":70,"department":"Services","name":"Photobean","title":"Nurse"},
    {"id":71,"userId":71,"department":"Services","name":"Photospace","title":"Sales Associate"},
    {"id":72,"userId":72,"department":"Research and Development","name":"Zoombox","title":"Professor"},
    {"id":73,"userId":73,"department":"Legal","name":"Leexo","title":"Professor"},
    {"id":74,"userId":74,"department":"Legal","name":"Twitternation","title":"Nuclear Power Engineer"},
    {"id":75,"userId":75,"department":"Human Resources","name":"Photobean","title":"Associate Professor"},
    {"id":76,"userId":76,"department":"Services","name":"Yakijo","title":"Health Coach IV"},
    {"id":77,"userId":77,"department":"Human Resources","name":"Flipopia","title":"Clinical Specialist"},
    {"id":78,"userId":78,"department":"Product Management","name":"Feednation","title":"Administrative Assistant II"},
    {"id":79,"userId":79,"department":"Legal","name":"Fivebridge","title":"VP Sales"},
    {"id":80,"userId":80,"department":"Engineering","name":"Kare","title":"Programmer Analyst IV"},
    {"id":81,"userId":81,"department":"Product Management","name":"Vinder","title":"Assistant Manager"},
    {"id":82,"userId":82,"department":"Product Management","name":"Gabtype","title":"Human Resources Manager"},
    {"id":83,"userId":83,"department":"Sales","name":"Thoughtworks","title":"Biostatistician II"},
    {"id":84,"userId":84,"department":"Product Management","name":"Myworks","title":"Mechanical Systems Engineer"},
    {"id":85,"userId":85,"department":"Support","name":"Jazzy","title":"Quality Engineer"},
    {"id":86,"userId":86,"department":"Sales","name":"Jabberbean","title":"Senior Quality Engineer"},
    {"id":87,"userId":87,"department":"Business Development","name":"Dynazzy","title":"Operator"},
    {"id":88,"userId":88,"department":"Services","name":"Blogpad","title":"VP Marketing"},
    {"id":89,"userId":89,"department":"Legal","name":"Topicstorm","title":"Technical Writer"},
    {"id":90,"userId":90,"department":"Engineering","name":"Brainverse","title":"Software Test Engineer III"},
    {"id":91,"userId":91,"department":"Product Management","name":"Bubblemix","title":"Analyst Programmer"},
    {"id":92,"userId":92,"department":"Research and Development","name":"Devpoint","title":"Recruiting Manager"},
    {"id":93,"userId":93,"department":"Human Resources","name":"Myworks","title":"Systems Administrator II"},
    {"id":94,"userId":94,"department":"Legal","name":"Gigaclub","title":"Biostatistician III"},
    {"id":95,"userId":95,"department":"Marketing","name":"Rhynoodle","title":"VP Marketing"},
    {"id":96,"userId":96,"department":"Marketing","name":"Youfeed","title":"Staff Scientist"},
    {"id":97,"userId":97,"department":"Training","name":"Fivespan","title":"Senior Financial Analyst"},
    {"id":98,"userId":98,"department":"Product Management","name":"Shuffledrive","title":"Staff Scientist"},
    {"id":99,"userId":99,"department":"Support","name":"Tagopia","title":"Database Administrator III"},
    {"id":100,"userId":100,"department":"Accounting","name":"Jaxspan","title":"Junior Executive"}];
  static async getCompanies() {
    const interval = IntervalService.getRandomNumberInRange(1000, 5000);
    return new Promise((res, rej) => {
      setTimeout(() => {
        res(this.companies);
      }, interval);
    });
  }
}
