import IntervalService from "../services/interval.service.js";

export default class AddressesDataService {
    static addresses = [{"id":1,"companyId":1,"address":"647 Jackson Circle","city":"Pekijing","state":null},
        {"id":2,"companyId":2,"address":"8282 Holmberg Street","city":"Libao","state":null},
        {"id":3,"companyId":3,"address":"747 Mariners Cove Place","city":"Erie","state":"Pennsylvania"},
        {"id":4,"companyId":4,"address":"77097 Warbler Junction","city":"Bitanjuan","state":null},
        {"id":5,"companyId":5,"address":"77 Elka Junction","city":"Dakingari","state":null},
        {"id":6,"companyId":6,"address":"8130 Prairieview Junction","city":"Kousséri","state":null},
        {"id":7,"companyId":7,"address":"4697 Linden Drive","city":"Blagnac","state":"Midi-Pyrénées"},
        {"id":8,"companyId":8,"address":"858 Anniversary Point","city":"Longshan","state":null},
        {"id":9,"companyId":9,"address":"4583 Daystar Court","city":"Janowiec","state":null},
        {"id":10,"companyId":10,"address":"7688 Chinook Lane","city":"Finzes","state":"Porto"},
        {"id":11,"companyId":11,"address":"658 Pearson Circle","city":"Chayek","state":null},
        {"id":12,"companyId":12,"address":"7099 Pleasure Way","city":"Berthierville","state":"Québec"},
        {"id":13,"companyId":13,"address":"4 Orin Crossing","city":"Wunat","state":null},
        {"id":14,"companyId":14,"address":"6958 Mcbride Drive","city":"Corinto","state":null},
        {"id":15,"companyId":15,"address":"0 Ridgeview Drive","city":"Miami","state":"Florida"},
        {"id":16,"companyId":16,"address":"1 Pleasure Drive","city":"Notodden","state":"Telemark"},
        {"id":17,"companyId":17,"address":"733 Helena Drive","city":"Arroteia","state":"Viana do Castelo"},
        {"id":18,"companyId":18,"address":"762 Mcguire Plaza","city":"Malin","state":null},
        {"id":19,"companyId":19,"address":"80 Daystar Drive","city":"La Cueva","state":null},
        {"id":20,"companyId":20,"address":"1 Mandrake Pass","city":"Tuanai","state":null},
        {"id":21,"companyId":21,"address":"3 Bluejay Pass","city":"Jargalant","state":null},
        {"id":22,"companyId":22,"address":"9133 Nancy Center","city":"Bila Krynytsya","state":null},
        {"id":23,"companyId":23,"address":"2966 7th Trail","city":"Calancuasan Norte","state":null},
        {"id":24,"companyId":24,"address":"05 Birchwood Circle","city":"Rockford","state":"Illinois"},
        {"id":25,"companyId":25,"address":"9043 Dexter Alley","city":"Parigi","state":null},
        {"id":26,"companyId":26,"address":"1981 Cardinal Avenue","city":"Bojongsari","state":null},
        {"id":27,"companyId":27,"address":"59810 Tennyson Pass","city":"Changtu","state":null},
        {"id":28,"companyId":28,"address":"499 Dexter Court","city":"Palanas","state":null},
        {"id":29,"companyId":29,"address":"38 Moland Place","city":"Dugulubgey","state":null},
        {"id":30,"companyId":30,"address":"3 Warner Park","city":"Zákynthos","state":null},
        {"id":31,"companyId":31,"address":"915 Transport Drive","city":"Coaraci","state":null},
        {"id":32,"companyId":32,"address":"7 New Castle Circle","city":"Thouars","state":"Poitou-Charentes"},
        {"id":33,"companyId":33,"address":"9 Eliot Street","city":"Bolkhov","state":null},
        {"id":34,"companyId":34,"address":"23 Fuller Court","city":"Bantogon","state":null},
        {"id":35,"companyId":35,"address":"91 Hoffman Junction","city":"El Matama","state":null},
        {"id":36,"companyId":36,"address":"08 Packers Circle","city":"Uchkulan","state":null},
        {"id":37,"companyId":37,"address":"155 Golf View Junction","city":"Sinjil","state":null},
        {"id":38,"companyId":38,"address":"24 Elgar Way","city":"Charlotte","state":"North Carolina"},
        {"id":39,"companyId":39,"address":"18366 Cambridge Crossing","city":"Washington","state":"District of Columbia"},
        {"id":40,"companyId":40,"address":"5 Meadow Ridge Junction","city":"Bardiyā","state":null},
        {"id":41,"companyId":41,"address":"5 Ryan Road","city":"La Mesa","state":null},
        {"id":42,"companyId":42,"address":"5 Grim Plaza","city":"Sovetskiy","state":null},
        {"id":43,"companyId":43,"address":"453 Merrick Alley","city":"Bandungan Timur","state":null},
        {"id":44,"companyId":44,"address":"05524 Almo Place","city":"Pandat","state":null},
        {"id":45,"companyId":45,"address":"5629 Forster Court","city":"Kurihashi","state":null},
        {"id":46,"companyId":46,"address":"749 Del Sol Place","city":"Orsha","state":null},
        {"id":47,"companyId":47,"address":"433 8th Place","city":"Aldergrove","state":"British Columbia"},
        {"id":48,"companyId":48,"address":"7458 Buell Point","city":"Yashiro","state":null},
        {"id":49,"companyId":49,"address":"99535 Hovde Way","city":"Denton","state":"Texas"},
        {"id":50,"companyId":50,"address":"56743 Sunfield Trail","city":"Kilju","state":null},
        {"id":51,"companyId":51,"address":"20687 Pepper Wood Crossing","city":"Boršice","state":null},
        {"id":52,"companyId":52,"address":"485 Grim Place","city":"Okinawa Número Uno","state":null},
        {"id":53,"companyId":53,"address":"01764 Ridgeview Court","city":"Néa Pélla","state":null},
        {"id":54,"companyId":54,"address":"7855 Russell Point","city":"Sukhirin","state":null},
        {"id":55,"companyId":55,"address":"35660 Bultman Crossing","city":"Světlá nad Sázavou","state":null},
        {"id":56,"companyId":56,"address":"1 Fairfield Court","city":"Gonghe","state":null},
        {"id":57,"companyId":57,"address":"341 Buena Vista Point","city":"Milano","state":"Lombardia"},
        {"id":58,"companyId":58,"address":"79166 Buhler Terrace","city":"Yuanjiazhuang","state":null},
        {"id":59,"companyId":59,"address":"61686 Banding Circle","city":"La Roche-sur-Yon","state":"Pays de la Loire"},
        {"id":60,"companyId":60,"address":"28567 Leroy Drive","city":"Shambu","state":null},
        {"id":61,"companyId":61,"address":"3281 Truax Circle","city":"Zubtsov","state":null},
        {"id":62,"companyId":62,"address":"93 Heath Parkway","city":"Kelburn","state":null},
        {"id":63,"companyId":63,"address":"83 Clemons Pass","city":"El Capulin","state":"Mexico"},
        {"id":64,"companyId":64,"address":"50 Twin Pines Center","city":"Kilkís","state":null},
        {"id":65,"companyId":65,"address":"48969 Dovetail Lane","city":"Néa Plágia","state":null},
        {"id":66,"companyId":66,"address":"22 Waubesa Place","city":"Örebro","state":"Örebro"},
        {"id":67,"companyId":67,"address":"24968 Weeping Birch Parkway","city":"Slutsk","state":null},
        {"id":68,"companyId":68,"address":"24329 Bashford Court","city":"Mirriah","state":null},
        {"id":69,"companyId":69,"address":"6 Blaine Trail","city":"Ujae","state":null},
        {"id":70,"companyId":70,"address":"53 Shopko Pass","city":"Guayaramerín","state":null},
        {"id":71,"companyId":71,"address":"3 Mariners Cove Alley","city":"Patía","state":null},
        {"id":72,"companyId":72,"address":"02 Nevada Center","city":"Iset’","state":null},
        {"id":73,"companyId":73,"address":"00183 Melby Avenue","city":"Santa Rosa","state":null},
        {"id":74,"companyId":74,"address":"9 Westend Lane","city":"Santiago","state":null},
        {"id":75,"companyId":75,"address":"5 Northland Plaza","city":"Banjar Parekan","state":null},
        {"id":76,"companyId":76,"address":"22313 Vidon Pass","city":"Brämhult","state":"Västra Götaland"},
        {"id":77,"companyId":77,"address":"509 Pleasure Street","city":"Iecava","state":null},
        {"id":78,"companyId":78,"address":"14686 Crescent Oaks Pass","city":"Jingxiyuan","state":null},
        {"id":79,"companyId":79,"address":"8173 Hanover Place","city":"Paços","state":"Aveiro"},
        {"id":80,"companyId":80,"address":"38 Hermina Junction","city":"Plácido de Castro","state":null},
        {"id":81,"companyId":81,"address":"18053 Jenna Trail","city":"Espanola","state":"Ontario"},
        {"id":82,"companyId":82,"address":"57 Tony Center","city":"Madjeouéni","state":null},
        {"id":83,"companyId":83,"address":"7 Fairview Pass","city":"Gambēla","state":null},
        {"id":84,"companyId":84,"address":"36460 Thompson Way","city":"Sugihmukti","state":null},
        {"id":85,"companyId":85,"address":"4 Mifflin Drive","city":"Sulaco","state":null},
        {"id":86,"companyId":86,"address":"48 Blue Bill Park Hill","city":"Bohdalov","state":null},
        {"id":87,"companyId":87,"address":"9 Tennessee Park","city":"Gobō","state":null},
        {"id":88,"companyId":88,"address":"6 Meadow Ridge Street","city":"Protaras","state":null},
        {"id":89,"companyId":89,"address":"931 Ohio Parkway","city":"Nāgarpur","state":null},
        {"id":90,"companyId":90,"address":"114 Veith Terrace","city":"Saint-Maurice","state":"Île-de-France"},
        {"id":91,"companyId":91,"address":"871 Portage Plaza","city":"Paris 13","state":"Île-de-France"},
        {"id":92,"companyId":92,"address":"20 Kinsman Plaza","city":"Amagi","state":null},
        {"id":93,"companyId":93,"address":"050 Blue Bill Park Place","city":"Bator","state":null},
        {"id":94,"companyId":94,"address":"004 Loftsgordon Court","city":"Yangtan","state":null},
        {"id":95,"companyId":95,"address":"3371 Toban Court","city":"Sano","state":null},
        {"id":96,"companyId":96,"address":"83368 Boyd Center","city":"Lazaro Cardenas","state":"Jalisco"},
        {"id":97,"companyId":97,"address":"3106 Delladonna Crossing","city":"La Aurora","state":"Jalisco"},
        {"id":98,"companyId":98,"address":"66 Meadow Valley Court","city":"Hepu","state":null},
        {"id":99,"companyId":99,"address":"61 Oneill Street","city":"Traganón","state":null},
        {"id":100,"companyId":100,"address":"5 Fulton Circle","city":"Citatah Kaler","state":null}];
    static async getAddresses(){
        const interval = IntervalService.getRandomNumberInRange(1000 , 5000)
        return new Promise((res,rej)=>{
            setTimeout(()=>{
                res( this.addresses)
            },interval)
        })
    }

}